import 'package:flutter/widgets.dart';
import 'package:intl/intl.dart';

class CurrencyOption {
  const CurrencyOption(this.code, this.name, this.symbol, this.flag);

  final String code;
  final String name;
  final String symbol;
  final String flag;

  bool matches(String query) {
    final value = query.trim().toLowerCase();
    return value.isEmpty ||
        code.toLowerCase().contains(value) ||
        name.toLowerCase().contains(value) ||
        symbol.toLowerCase().contains(value);
  }
}

const worldCurrencies = <CurrencyOption>[
  CurrencyOption('AED', 'UAE Dirham', 'د.إ', '🇦🇪'),
  CurrencyOption('AFN', 'Afghan Afghani', '؋', '🇦🇫'),
  CurrencyOption('ALL', 'Albanian Lek', 'L', '🇦🇱'),
  CurrencyOption('AMD', 'Armenian Dram', '֏', '🇦🇲'),
  CurrencyOption('ANG', 'Netherlands Antillean Guilder', 'ƒ', '🇨🇼'),
  CurrencyOption('AOA', 'Angolan Kwanza', 'Kz', '🇦🇴'),
  CurrencyOption('ARS', 'Argentine Peso', r'$', '🇦🇷'),
  CurrencyOption('AUD', 'Australian Dollar', r'A$', '🇦🇺'),
  CurrencyOption('AWG', 'Aruban Florin', 'ƒ', '🇦🇼'),
  CurrencyOption('AZN', 'Azerbaijani Manat', '₼', '🇦🇿'),
  CurrencyOption('BAM', 'Bosnia-Herzegovina Mark', 'KM', '🇧🇦'),
  CurrencyOption('BBD', 'Barbadian Dollar', r'Bds$', '🇧🇧'),
  CurrencyOption('BDT', 'Bangladeshi Taka', '৳', '🇧🇩'),
  CurrencyOption('BGN', 'Bulgarian Lev', 'лв', '🇧🇬'),
  CurrencyOption('BHD', 'Bahraini Dinar', 'د.ب', '🇧🇭'),
  CurrencyOption('BIF', 'Burundian Franc', 'FBu', '🇧🇮'),
  CurrencyOption('BMD', 'Bermudian Dollar', r'BD$', '🇧🇲'),
  CurrencyOption('BND', 'Brunei Dollar', r'B$', '🇧🇳'),
  CurrencyOption('BOB', 'Bolivian Boliviano', 'Bs', '🇧🇴'),
  CurrencyOption('BRL', 'Brazilian Real', r'R$', '🇧🇷'),
  CurrencyOption('BSD', 'Bahamian Dollar', r'B$', '🇧🇸'),
  CurrencyOption('BTN', 'Bhutanese Ngultrum', 'Nu.', '🇧🇹'),
  CurrencyOption('BWP', 'Botswana Pula', 'P', '🇧🇼'),
  CurrencyOption('BYN', 'Belarusian Ruble', 'Br', '🇧🇾'),
  CurrencyOption('BZD', 'Belize Dollar', r'BZ$', '🇧🇿'),
  CurrencyOption('CAD', 'Canadian Dollar', r'C$', '🇨🇦'),
  CurrencyOption('CDF', 'Congolese Franc', 'FC', '🇨🇩'),
  CurrencyOption('CHF', 'Swiss Franc', 'CHF', '🇨🇭'),
  CurrencyOption('CLP', 'Chilean Peso', r'CLP$', '🇨🇱'),
  CurrencyOption('CNY', 'Chinese Yuan', '¥', '🇨🇳'),
  CurrencyOption('COP', 'Colombian Peso', r'COL$', '🇨🇴'),
  CurrencyOption('CRC', 'Costa Rican Colón', '₡', '🇨🇷'),
  CurrencyOption('CUP', 'Cuban Peso', r'₱', '🇨🇺'),
  CurrencyOption('CVE', 'Cape Verdean Escudo', r'Esc', '🇨🇻'),
  CurrencyOption('CZK', 'Czech Koruna', 'Kč', '🇨🇿'),
  CurrencyOption('DJF', 'Djiboutian Franc', 'Fdj', '🇩🇯'),
  CurrencyOption('DKK', 'Danish Krone', 'kr', '🇩🇰'),
  CurrencyOption('DOP', 'Dominican Peso', r'RD$', '🇩🇴'),
  CurrencyOption('DZD', 'Algerian Dinar', 'دج', '🇩🇿'),
  CurrencyOption('EGP', 'Egyptian Pound', 'E£', '🇪🇬'),
  CurrencyOption('ERN', 'Eritrean Nakfa', 'Nfk', '🇪🇷'),
  CurrencyOption('ETB', 'Ethiopian Birr', 'Br', '🇪🇹'),
  CurrencyOption('EUR', 'Euro', '€', '🇪🇺'),
  CurrencyOption('FJD', 'Fijian Dollar', r'FJ$', '🇫🇯'),
  CurrencyOption('FKP', 'Falkland Islands Pound', '£', '🇫🇰'),
  CurrencyOption('GBP', 'British Pound', '£', '🇬🇧'),
  CurrencyOption('GEL', 'Georgian Lari', '₾', '🇬🇪'),
  CurrencyOption('GHS', 'Ghanaian Cedi', '₵', '🇬🇭'),
  CurrencyOption('GIP', 'Gibraltar Pound', '£', '🇬🇮'),
  CurrencyOption('GMD', 'Gambian Dalasi', 'D', '🇬🇲'),
  CurrencyOption('GNF', 'Guinean Franc', 'FG', '🇬🇳'),
  CurrencyOption('GTQ', 'Guatemalan Quetzal', 'Q', '🇬🇹'),
  CurrencyOption('GYD', 'Guyanese Dollar', r'G$', '🇬🇾'),
  CurrencyOption('HKD', 'Hong Kong Dollar', r'HK$', '🇭🇰'),
  CurrencyOption('HNL', 'Honduran Lempira', 'L', '🇭🇳'),
  CurrencyOption('HTG', 'Haitian Gourde', 'G', '🇭🇹'),
  CurrencyOption('HUF', 'Hungarian Forint', 'Ft', '🇭🇺'),
  CurrencyOption('IDR', 'Indonesian Rupiah', 'Rp', '🇮🇩'),
  CurrencyOption('ILS', 'Israeli New Shekel', '₪', '🇮🇱'),
  CurrencyOption('INR', 'Indian Rupee', '₹', '🇮🇳'),
  CurrencyOption('IQD', 'Iraqi Dinar', 'ع.د', '🇮🇶'),
  CurrencyOption('IRR', 'Iranian Rial', '﷼', '🇮🇷'),
  CurrencyOption('ISK', 'Icelandic Króna', 'kr', '🇮🇸'),
  CurrencyOption('JMD', 'Jamaican Dollar', r'J$', '🇯🇲'),
  CurrencyOption('JOD', 'Jordanian Dinar', 'د.ا', '🇯🇴'),
  CurrencyOption('JPY', 'Japanese Yen', '¥', '🇯🇵'),
  CurrencyOption('KES', 'Kenyan Shilling', 'KSh', '🇰🇪'),
  CurrencyOption('KGS', 'Kyrgyzstani Som', 'с', '🇰🇬'),
  CurrencyOption('KHR', 'Cambodian Riel', '៛', '🇰🇭'),
  CurrencyOption('KMF', 'Comorian Franc', 'CF', '🇰🇲'),
  CurrencyOption('KRW', 'South Korean Won', '₩', '🇰🇷'),
  CurrencyOption('KWD', 'Kuwaiti Dinar', 'د.ك', '🇰🇼'),
  CurrencyOption('KYD', 'Cayman Islands Dollar', r'CI$', '🇰🇾'),
  CurrencyOption('KZT', 'Kazakhstani Tenge', '₸', '🇰🇿'),
  CurrencyOption('LAK', 'Lao Kip', '₭', '🇱🇦'),
  CurrencyOption('LBP', 'Lebanese Pound', 'ل.ل', '🇱🇧'),
  CurrencyOption('LKR', 'Sri Lankan Rupee', 'Rs', '🇱🇰'),
  CurrencyOption('LRD', 'Liberian Dollar', r'L$', '🇱🇷'),
  CurrencyOption('LSL', 'Lesotho Loti', 'L', '🇱🇸'),
  CurrencyOption('LYD', 'Libyan Dinar', 'ل.د', '🇱🇾'),
  CurrencyOption('MAD', 'Moroccan Dirham', 'د.م.', '🇲🇦'),
  CurrencyOption('MDL', 'Moldovan Leu', 'L', '🇲🇩'),
  CurrencyOption('MGA', 'Malagasy Ariary', 'Ar', '🇲🇬'),
  CurrencyOption('MKD', 'Macedonian Denar', 'ден', '🇲🇰'),
  CurrencyOption('MMK', 'Myanmar Kyat', 'K', '🇲🇲'),
  CurrencyOption('MNT', 'Mongolian Tögrög', '₮', '🇲🇳'),
  CurrencyOption('MOP', 'Macanese Pataca', r'MOP$', '🇲🇴'),
  CurrencyOption('MRU', 'Mauritanian Ouguiya', 'UM', '🇲🇷'),
  CurrencyOption('MUR', 'Mauritian Rupee', '₨', '🇲🇺'),
  CurrencyOption('MVR', 'Maldivian Rufiyaa', 'Rf', '🇲🇻'),
  CurrencyOption('MWK', 'Malawian Kwacha', 'MK', '🇲🇼'),
  CurrencyOption('MXN', 'Mexican Peso', r'MX$', '🇲🇽'),
  CurrencyOption('MYR', 'Malaysian Ringgit', 'RM', '🇲🇾'),
  CurrencyOption('MZN', 'Mozambican Metical', 'MT', '🇲🇿'),
  CurrencyOption('NAD', 'Namibian Dollar', r'N$', '🇳🇦'),
  CurrencyOption('NGN', 'Nigerian Naira', '₦', '🇳🇬'),
  CurrencyOption('NIO', 'Nicaraguan Córdoba', r'C$', '🇳🇮'),
  CurrencyOption('NOK', 'Norwegian Krone', 'kr', '🇳🇴'),
  CurrencyOption('NPR', 'Nepalese Rupee', 'रू', '🇳🇵'),
  CurrencyOption('NZD', 'New Zealand Dollar', r'NZ$', '🇳🇿'),
  CurrencyOption('OMR', 'Omani Rial', 'ر.ع.', '🇴🇲'),
  CurrencyOption('PAB', 'Panamanian Balboa', 'B/.', '🇵🇦'),
  CurrencyOption('PEN', 'Peruvian Sol', 'S/', '🇵🇪'),
  CurrencyOption('PGK', 'Papua New Guinean Kina', 'K', '🇵🇬'),
  CurrencyOption('PHP', 'Philippine Peso', '₱', '🇵🇭'),
  CurrencyOption('PKR', 'Pakistani Rupee', '₨', '🇵🇰'),
  CurrencyOption('PLN', 'Polish Złoty', 'zł', '🇵🇱'),
  CurrencyOption('PYG', 'Paraguayan Guaraní', '₲', '🇵🇾'),
  CurrencyOption('QAR', 'Qatari Riyal', 'ر.ق', '🇶🇦'),
  CurrencyOption('RON', 'Romanian Leu', 'lei', '🇷🇴'),
  CurrencyOption('RSD', 'Serbian Dinar', 'дин', '🇷🇸'),
  CurrencyOption('RUB', 'Russian Ruble', '₽', '🇷🇺'),
  CurrencyOption('RWF', 'Rwandan Franc', 'FRw', '🇷🇼'),
  CurrencyOption('SAR', 'Saudi Riyal', 'ر.س', '🇸🇦'),
  CurrencyOption('SBD', 'Solomon Islands Dollar', r'SI$', '🇸🇧'),
  CurrencyOption('SCR', 'Seychellois Rupee', '₨', '🇸🇨'),
  CurrencyOption('SDG', 'Sudanese Pound', 'ج.س.', '🇸🇩'),
  CurrencyOption('SEK', 'Swedish Krona', 'kr', '🇸🇪'),
  CurrencyOption('SGD', 'Singapore Dollar', r'S$', '🇸🇬'),
  CurrencyOption('SHP', 'Saint Helena Pound', '£', '🇸🇭'),
  CurrencyOption('SLE', 'Sierra Leonean Leone', 'Le', '🇸🇱'),
  CurrencyOption('SOS', 'Somali Shilling', 'Sh', '🇸🇴'),
  CurrencyOption('SRD', 'Surinamese Dollar', r'Sr$', '🇸🇷'),
  CurrencyOption('SSP', 'South Sudanese Pound', '£', '🇸🇸'),
  CurrencyOption('STN', 'São Tomé and Príncipe Dobra', 'Db', '🇸🇹'),
  CurrencyOption('SYP', 'Syrian Pound', '£S', '🇸🇾'),
  CurrencyOption('SZL', 'Swazi Lilangeni', 'L', '🇸🇿'),
  CurrencyOption('THB', 'Thai Baht', '฿', '🇹🇭'),
  CurrencyOption('TJS', 'Tajikistani Somoni', 'ЅМ', '🇹🇯'),
  CurrencyOption('TMT', 'Turkmenistani Manat', 'm', '🇹🇲'),
  CurrencyOption('TND', 'Tunisian Dinar', 'د.ت', '🇹🇳'),
  CurrencyOption('TOP', 'Tongan Paʻanga', r'T$', '🇹🇴'),
  CurrencyOption('TRY', 'Turkish Lira', '₺', '🇹🇷'),
  CurrencyOption('TTD', 'Trinidad and Tobago Dollar', r'TT$', '🇹🇹'),
  CurrencyOption('TWD', 'New Taiwan Dollar', r'NT$', '🇹🇼'),
  CurrencyOption('TZS', 'Tanzanian Shilling', 'TSh', '🇹🇿'),
  CurrencyOption('UAH', 'Ukrainian Hryvnia', '₴', '🇺🇦'),
  CurrencyOption('UGX', 'Ugandan Shilling', 'USh', '🇺🇬'),
  CurrencyOption('USD', 'US Dollar', r'$', '🇺🇸'),
  CurrencyOption('UYU', 'Uruguayan Peso', r'$U', '🇺🇾'),
  CurrencyOption('UZS', 'Uzbekistani Som', 'soʻm', '🇺🇿'),
  CurrencyOption('VES', 'Venezuelan Bolívar', 'Bs.', '🇻🇪'),
  CurrencyOption('VND', 'Vietnamese Đồng', '₫', '🇻🇳'),
  CurrencyOption('VUV', 'Vanuatu Vatu', 'VT', '🇻🇺'),
  CurrencyOption('WST', 'Samoan Tālā', r'WS$', '🇼🇸'),
  CurrencyOption('XAF', 'Central African CFA Franc', 'FCFA', '🌍'),
  CurrencyOption('XCD', 'East Caribbean Dollar', r'EC$', '🏝️'),
  CurrencyOption('XOF', 'West African CFA Franc', 'CFA', '🌍'),
  CurrencyOption('XPF', 'CFP Franc', '₣', '🏝️'),
  CurrencyOption('YER', 'Yemeni Rial', '﷼', '🇾🇪'),
  CurrencyOption('ZAR', 'South African Rand', 'R', '🇿🇦'),
  CurrencyOption('ZMW', 'Zambian Kwacha', 'ZK', '🇿🇲'),
  CurrencyOption('ZWL', 'Zimbabwean Dollar', r'Z$', '🇿🇼'),
];

CurrencyOption currencyForCode(String code) => worldCurrencies.firstWhere(
      (item) => item.code == code.toUpperCase(),
      orElse: () => const CurrencyOption('INR', 'Indian Rupee', '₹', '🇮🇳'),
    );

String formatMoney(double value, String currencyCode) {
  final currency = currencyForCode(currencyCode);
  return NumberFormat.currency(
    locale: 'en',
    name: currency.code,
    symbol: currency.symbol,
    decimalDigits: 0,
  ).format(value);
}

String defaultCurrencyCodeForLocale(Locale locale) {
  const countryCurrencies = <String, String>{
    'AE': 'AED',
    'AF': 'AFN',
    'AL': 'ALL',
    'AM': 'AMD',
    'AR': 'ARS',
    'AT': 'EUR',
    'AU': 'AUD',
    'AZ': 'AZN',
    'BD': 'BDT',
    'BE': 'EUR',
    'BG': 'BGN',
    'BH': 'BHD',
    'BR': 'BRL',
    'BT': 'BTN',
    'BW': 'BWP',
    'BY': 'BYN',
    'CA': 'CAD',
    'CH': 'CHF',
    'CL': 'CLP',
    'CN': 'CNY',
    'CO': 'COP',
    'CZ': 'CZK',
    'DE': 'EUR',
    'DK': 'DKK',
    'DZ': 'DZD',
    'EG': 'EGP',
    'ES': 'EUR',
    'ET': 'ETB',
    'FI': 'EUR',
    'FJ': 'FJD',
    'FR': 'EUR',
    'GB': 'GBP',
    'GE': 'GEL',
    'GH': 'GHS',
    'GR': 'EUR',
    'HK': 'HKD',
    'HR': 'EUR',
    'HU': 'HUF',
    'ID': 'IDR',
    'IE': 'EUR',
    'IL': 'ILS',
    'IN': 'INR',
    'IQ': 'IQD',
    'IR': 'IRR',
    'IS': 'ISK',
    'IT': 'EUR',
    'JM': 'JMD',
    'JO': 'JOD',
    'JP': 'JPY',
    'KE': 'KES',
    'KG': 'KGS',
    'KH': 'KHR',
    'KR': 'KRW',
    'KW': 'KWD',
    'KZ': 'KZT',
    'LA': 'LAK',
    'LB': 'LBP',
    'LK': 'LKR',
    'MA': 'MAD',
    'MM': 'MMK',
    'MN': 'MNT',
    'MU': 'MUR',
    'MV': 'MVR',
    'MX': 'MXN',
    'MY': 'MYR',
    'NG': 'NGN',
    'NL': 'EUR',
    'NO': 'NOK',
    'NP': 'NPR',
    'NZ': 'NZD',
    'OM': 'OMR',
    'PE': 'PEN',
    'PH': 'PHP',
    'PK': 'PKR',
    'PL': 'PLN',
    'PT': 'EUR',
    'QA': 'QAR',
    'RO': 'RON',
    'RS': 'RSD',
    'RU': 'RUB',
    'SA': 'SAR',
    'SE': 'SEK',
    'SG': 'SGD',
    'TH': 'THB',
    'TN': 'TND',
    'TR': 'TRY',
    'TW': 'TWD',
    'TZ': 'TZS',
    'UA': 'UAH',
    'UG': 'UGX',
    'US': 'USD',
    'UZ': 'UZS',
    'VN': 'VND',
    'ZA': 'ZAR',
    'ZM': 'ZMW',
  };
  return countryCurrencies[locale.countryCode?.toUpperCase()] ?? 'USD';
}
